<?php

namespace BlogBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{

    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder("u")
            ->where("u.email = :email OR u.username = :username")
            ->setParameter("email", $username)
            ->setParameter("username", $username)
            ->getQuery()
            ->getOneOrNullResult();

    }
}
